site_name: RoPython Documentation
site_url: https://parker02311.github.io/ropython/
site_description: 'Documentation for RoPython'
site_author: 'parker02311'
docs_dir: docs/
repo_name: 'parker02311/ropython'
repo_url: 'https://github.com/parker02311/ropython'
nav:
    - Overview: index.md
    - Api Reference
        - Client: ropython/client
theme:
  name: 'material'
  palette:
    scheme: slate
    primary: black
    accent: green
plugins:
  - search
  - gen-files:
      scripts:
        - docs/gen_doc_stubs.py
  - mkdocstrings:
      watch:
        - ropython
      handlers:
        python:
          setup_commands:
          - import sys
          - sys.path.append("docs")
          selection:
            new_path_syntax: yes
          rendering:
            show_if_no_docstring: yes
            show_signature_annotations: yes
            show_root_heading: yes
  - mermaid2:
      arguments:
        theme: dark
