name: MkDocs Deploy

on:
  workflow_dispatch:
    inputs:
      name:
        description: "MkDocs Deploy"
  push:
    branches:
      - master

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v1

      - run: pip install mkdocs-material mkdocstrings httpx mkdocs-gen-files mkdocs-mermaid2-plugin
      - run: mkdocs gh-deploy
